# Generated by Django 3.2.7 on 2021-11-08 08:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_restaurant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, help_text='Warning editing this field will change the About Us section on the home page! Clear the field to display the default text.'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=cloudinary.models.CloudinaryField(default='placeholder', help_text='Image of restaurant menu.', max_length=255, verbose_name='image'),
        ),
    ]
