# Generated by Django 3.2.7 on 2021-10-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_requirements',
            field=models.TextField(blank=True),
        ),
    ]
