# Generated by Django 3.2.7 on 2021-10-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0003_alter_booking_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table_numbers',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
