# Generated by Django 3.2.7 on 2021-10-27 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0004_booking_table_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-time']},
        ),
    ]
