# Generated by Django 3.2.7 on 2021-11-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0006_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
