# Generated by Django 3.2.7 on 2021-11-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0007_booking_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='updated',
            field=models.BooleanField(default=True),
        ),
    ]
