# Generated by Django 3.2.7 on 2021-11-03 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0009_auto_20211103_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'time']},
        ),
    ]
